version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    links:
      - fastly-exporter:fastly-exporter
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:7.2.2
    env_file:
      - ./grafana/config.env
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana

  fastly-exporter:
    image: mrnetops/fastly-exporter:4
    command: -namespace fastly -service ${SID} 
    environment:
      - FASTLY_API_TOKEN=${FASTLY_API_TOKEN}
    expose:
      - 8080
    ports:
     - 8080:8080

