groups:
  - name: altitude
    rules:

    - alert: fastlyAltitude2022SlackDemo
      expr: fastly_account:requests > 0
      labels:
        job: 'fastlyAltitude'
        severity: warning
      annotations:
        description: 'Working!'
