groups:
  - name: datacenter
    rules:

    ##
    ## Metrics
    ##

    - record: fastly_datacenter:requests
      expr: sum(rate(fastly_rt_requests_total[120s])) by (datacenter)
    - record: fastly_datacenter:4xx_ratio
      expr: sum(rate(fastly_rt_status_group_total{status_group="4xx"}[120s])) by (datacenter) / sum(rate(fastly_rt_status_group_total[120s])) by (datacenter)
    - record: fastly_datacenter:5xx_ratio
      expr: sum(rate(fastly_rt_status_group_total{status_group="5xx"}[120s])) by (datacenter) / sum(rate(fastly_rt_status_group_total[120s])) by (datacenter)
    - record: fastly_datacenter:errors_ratio
      expr: sum(rate(fastly_rt_errors_total[120s])) by (datacenter) / fastly_datacenter:requests
    - record: fastly_datacenter:latency_p50_seconds
      expr: histogram_quantile(0.5,sum(rate(fastly_rt_miss_duration_seconds_bucket[120s])) by (le,datacenter))
    - record: fastly_datacenter:latency_p99_seconds
      expr: histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket[120s])) by (le,datacenter))

    ##
    ## Thresholds
    ##

    - record: fastly_datacenter:4xx_warn_ratio
      expr: 0.0045+0*fastly_datacenter:alerts_recently{alertname="fastlyDatacenter4xxPercent"} or 0.006+0*fastly_datacenter:requests
    - record: fastly_datacenter:5xx_warn_ratio
      expr: 0.0375+0*fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"} or 0.05+0*fastly_datacenter:requests
    - record: fastly_datacenter:error_warn_ratio
      expr: 0.0375+0*fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"} or 0.05+0*fastly_datacenter:requests
    # 826ms would put you in the worst 20% of sites
    # Per https://www.littledata.io/average/server-response-time
    - record: fastly_datacenter:latency_p50_warn_seconds
      expr: 0.620+0*fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"} or 0.826+0*fastly_datacenter:requests
    # Our P50 latency, for example, tends to be less than one third of our P99 latency
    # Per https://medium.com/@djsmith42/how-to-metric-edafaf959fc7
    - record: fastly_datacenter:latency_p99_warn_seconds
      expr: 1.859+0*fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"} or 2.478+0*fastly_datacenter:requests


    #
    # Records - Alerts
    #

    - record: fastly_datacenter:alerts
      expr: count(ALERTS{alertstate="firing", datacenter=~".+"}) by (alertname, datacenter)
    - record: fastly_datacenter:alerts_recently
      expr: sum(sum_over_time(ALERTS{alertstate="firing", datacenter=~".+"}[10m])) by (alertname,datacenter)
    
    #
    # Record - Criteria
    #

    # notice: some minimum level of traffic over time
    - record: fastly_datacenter:criteria_notice
      expr: min_over_time(fastly_datacenter:requests[5m]) > 1
    # warning: top 20% of notice
    - record: fastly_datacenter:criteria_warning
      #expr: topk(scalar(count(fastly_datacenter:criteria_notice) * .2), fastly_datacenter:criteria_notice) or fastly_datacenter:alerts_recently
      expr: topk(scalar(count(fastly_datacenter:criteria_notice) * .2), sum(fastly_datacenter:criteria_notice) by (datacenter)) or count(fastly_datacenter:alerts_recently) by (datacenter)

    #
    # Alert Rules
    #

    - alert: fastlyDatacenter4xxPercent
      expr: (avg_over_time(fastly_datacenter:4xx_ratio[5m]) > fastly_datacenter:4xx_warn_ratio) and fastly_datacenter:criteria_warning
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenter4xxPercentMOT
      expr: (max_over_time((min_over_time(fastly_datacenter:4xx_ratio[5m]))[10m:15s]) > fastly_datacenter:4xx_warn_ratio) and fastly_datacenter:criteria_warning
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenter5xxPercent
      expr: '((avg_over_time(datacenter:fastlyDatacenter5xxPercent[5m]) > 5) or (datacenter:fastlyDatacenter5xxPercent > 2.5 and datacenter:alerting{alertname="fastlyDatacenter5xxPercent"})) and datacenter:alertWarning'
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenterErrorPercent
      expr: '((avg_over_time(datacenter:fastlyDatacenterErrorPercent[5m]) > 5) or (datacenter:fastlyDatacenterErrorPercent > 2.5 and datacenter:alerting{alertname="fastlyDatacenterErrorPercent"})) and datacenter:alertWarning'
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenterP50Latency
      expr: '((avg_over_time(datacenter:fastlyDatacenterP50Latency[5m]) > 1.2) or (datacenter:fastlyDatacenterP50Latency > .312 and datacenter:alerting{alertname="fastlyDatacenterP50Latency"})) and datacenter:alertWarning'
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2fs" $value }})'
    - alert: fastlyDatacenter4xxPercentMOT
      expr: 'max_over_time(datacenter:fastlyDatacenter4xxPercent[10m]) > 60 and datacenter:alertWarning'
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenter5xxPercentMOT
      expr: 'max_over_time(datacenter:fastlyDatacenter5xxPercent[10m]) > 5 and datacenter:alertWarning'
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenterErrorPercentMOT
      expr: 'max_over_time((min_over_time(datacenter:fastlyDatacenterErrorPercent[3m]))[10m:15s]) > 5 and datacenter:alertWarning'
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2f%%" $value }})'
    - alert: fastlyDatacenterP50LatencyMOT
      expr: 'max_over_time(datacenter:fastlyDatacenterP50Latency[10m]) > 1.2 and datacenter:alertWarning'
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{ printf "%.2fs" $value }})'
