groups:
  - name: datacenter
    rules:

    ##
    ## Metrics
    ##

    - record: fastly_datacenter:requests
      expr: sum(rate(fastly_rt_requests_total[120s])) by (datacenter)
    - record: fastly_datacenter:4xx_ratio
      expr: |
        sum(rate(fastly_rt_status_group_total{status_group="4xx"}[120s])) by (datacenter) 
        / sum(rate(fastly_rt_status_group_total[120s])) by (datacenter)
    - record: fastly_datacenter:5xx_ratio
      expr: |
        sum(rate(fastly_rt_status_group_total{status_group="5xx"}[120s])) by (datacenter) 
        / sum(rate(fastly_rt_status_group_total[120s])) by (datacenter)
    - record: fastly_datacenter:errors_ratio
      expr: |
        sum(rate(fastly_rt_errors_total[120s])) by (datacenter) 
        / fastly_datacenter:requests
    - record: fastly_datacenter:latency_p50_seconds
      expr: histogram_quantile(0.5,sum(rate(fastly_rt_miss_duration_seconds_bucket[120s])) by (le,datacenter))
    - record: fastly_datacenter:latency_p99_seconds
      expr: histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket[120s])) by (le,datacenter))

    ##
    ## Thresholds
    ##

    - record: fastly_datacenter:4xx_warn_ratio
      expr: |
        0.45+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter4xxPercent"}) by (datacenter)
        or 0.6+0*fastly_datacenter:requests
    - record: fastly_datacenter:5xx_warn_ratio
      expr: |
        0.0375+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"}) by (datacenter)
        or 0.05+0*fastly_datacenter:requests
    - record: fastly_datacenter:errors_warn_ratio
      expr: |
        0.0375+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"}) by (datacenter)
        or 0.05+0*fastly_datacenter:requests
    # 826ms would put you in the worst 20% of sites
    # Per https://www.littledata.io/average/server-response-time
    - record: fastly_datacenter:latency_p50_warn_seconds
      expr: |
        0.620+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"}) by (datacenter)
        or 0.826+0*fastly_datacenter:requests
    # Our P50 latency, for example, tends to be less than one third of our P99 latency
    # Per https://medium.com/@djsmith42/how-to-metric-edafaf959fc7
    - record: fastly_datacenter:latency_p99_warn_seconds
      expr: |
        1.859+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"}) by (datacenter)
        or 2.478+0*fastly_datacenter:requests

    #
    # Records - Alerts
    #

    - record: fastly_datacenter:alerts
      expr: count(ALERTS{alertstate="firing", datacenter=~".+"}) by (alertname, datacenter)
    - record: fastly_datacenter:alerts_recently
      expr: sum(sum_over_time(ALERTS{alertstate="firing", datacenter=~".+"}[1h])) by (alertname,datacenter)
    
    #
    # Record - Criteria
    #

    # notice: some minimum level of traffic over time
    - record: fastly_datacenter:criteria_notice
      expr: min_over_time(fastly_datacenter:requests[5m]) > 1
    - record: fastly_datacenter:criteria_notice_recently
      expr: count_over_time(fastly_datacenter:criteria_notice[1h])
    # warning: top 20% of notice
    - record: fastly_datacenter:criteria_warning
      expr: topk(scalar(count(fastly_datacenter:criteria_notice) * .2), sum(fastly_datacenter:criteria_notice) by (datacenter)) or count(fastly_datacenter:alerts_recently) by (datacenter)
    - record: fastly_datacenter:criteria_warning_recently
      expr: count_over_time(fastly_datacenter:criteria_warning[1h])

    #
    # Alert Rules
    #

    - alert: fastlyDatacenter4xxPercent
      expr: |
        (fastly_datacenter:4xx_ratio > fastly_datacenter:4xx_warn_ratio) 
        and (fastly_datacenter:criteria_warning_recently)
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenter4xxPercentMOT3
      expr: |
        (max_over_time((min_over_time(fastly_datacenter:4xx_ratio[3m]))[10m:15s]) > fastly_datacenter:4xx_warn_ratio) 
        and fastly_datacenter:criteria_warning_recently
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenter4xxPercentMOT5
      expr: |
        (max_over_time((min_over_time(fastly_datacenter:4xx_ratio[5m]))[10m:15s]) > fastly_datacenter:4xx_warn_ratio) 
        and fastly_datacenter:criteria_warning_recently
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenter4xxPercentMOT10
      expr: |
        (max_over_time((min_over_time(fastly_datacenter:4xx_ratio[10m]))[10m:15s]) > fastly_datacenter:4xx_warn_ratio) 
        and fastly_datacenter:criteria_warning_recently
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenter5xxPercent
      expr: |
        (fastly_datacenter:5xx_ratio > fastly_datacenter:5xx_warn_ratio) 
        and (fastly_datacenter:criteria_warning_recently)
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenterErrorPercent
      expr: |
        (fastly_datacenter:errors_ratio > fastly_datacenter:errors_warn_ratio) 
        and (fastly_datacenter:criteria_warning_recently)
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenterP50Latency
      expr: |
        (fastly_datacenter:latency_p50_seconds > fastly_datacenter:latency_p50_warn_seconds) 
        and (fastly_datacenter:criteria_warning_recently)
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
    - alert: fastlyDatacenterP99Latency
      expr: |
        (fastly_datacenter:latency_p99_seconds > fastly_datacenter:latency_p99_warn_seconds) 
        and (fastly_datacenter:criteria_warning_recently)
      for: 10m
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
    - alert: fastlyDatacenterP99LatencyMOT3
      expr: |
        (max_over_time((min_over_time(fastly_datacenter:latency_p99_seconds[3m]))[10m:15s]) > fastly_datacenter:latency_p99_warn_seconds) 
        and (fastly_datacenter:criteria_warning_recently)
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
