groups:
  - name: origin
    rules:

    ##
    ## Basic Transformations
    ## - counter -> rate
    ## - histogram -> latency
    ## - etc
    ##

    - record: fastly_origin:requests
      expr: sum(rate(fastly_origin_responses_total[120s])) by (origin,service_id,service_name)
    - record: fastly_origin:4xx_ratio
      expr: |
        sum(rate(fastly_origin_status_group_total{status_group="4xx"}[120s])) by (origin,service_id,service_name) 
        / sum(rate(fastly_origin_status_group_total[120s])) by (origin,service_id,service_name)
    - record: fastly_origin:5xx_ratio
      expr: |
        sum(rate(fastly_origin_status_group_total{status_group="5xx"}[120s])) by (origin,service_id,service_name) 
        / sum(rate(fastly_origin_status_group_total[120s])) by (origin,service_id,service_name)
    - record: fastly_origin:errors_ratio
      expr: |
        sum(rate(fastly_rt_errors_total[120s])) by (origin,service_id,service_name) 
        / fastly_origin:requests
    - record: fastly_origin:latency_p50_seconds
      expr: histogram_quantile(0.5,sum(rate(fastly_origin_latency_seconds_bucket[120s])) by (le,origin,service_id,service_name))
    - record: fastly_origin:latency_p99_seconds
      expr: histogram_quantile(0.99,sum(rate(fastly_origin_latency_seconds_bucket[120s])) by (le,origin,service_id,service_name))

    ##
    ## Thresholds
    ## - Hysteresis, for more details see
    ##   https://promcon.io/2019-munich/talks/improved-alerting-with-prometheus-and-alertmanager/
    ##

    - record: fastly_origin:4xx_warn_ratio
      expr: |
        0.45+0*count(fastly_origin:alerts_recently{alertname="fastlyOrigin4xxPercent"}) by (origin,service_id,service_name)
        or 0.6+0*fastly_origin:requests
    - record: fastly_origin:5xx_warn_ratio
      expr: |
        0.0375+0*count(fastly_origin:alerts_recently{alertname="fastlyOrigin5xxPercent"}) by (origin,service_id,service_name)
        or 0.05+0*fastly_origin:requests
    - record: fastly_origin:errors_warn_ratio
      expr: |
        0.0375+0*count(fastly_origin:alerts_recently{alertname="fastlyOriginErrorPercent"}) by (origin,service_id,service_name)
        or 0.05+0*fastly_origin:requests
    # 826ms would put you in the worst 20% of sites
    # Per https://www.littledata.io/average/server-response-time
    - record: fastly_origin:latency_p50_warn_seconds
      expr: |
        0.620+0*count(fastly_origin:alerts_recently{alertname="fastlyOriginP50Latency"}) by (origin,service_id,service_name)
        or 0.826+0*fastly_origin:requests
    # Our P50 latency, for example, tends to be less than one third of our P99 latency
    # Per https://medium.com/@djsmith42/how-to-metric-edafaf959fc7
    - record: fastly_origin:latency_p99_warn_seconds
      expr: |
        1.859+0*count(fastly_origin:alerts_recently{alertname="fastlyOriginP99Latency"}) by (origin,service_id,service_name)
        or 2.478+0*fastly_origin:requests

    ##
    ## Alert Status
    ##

    - record: fastly_origin:alerts
      expr: count(ALERTS{alertstate="firing", origin=~".+", service_id=~".+", service_name=~".+"}) by (alertname,origin,service_id,service_name)
    - record: fastly_origin:alerts_recently
      expr: sum(sum_over_time(ALERTS{alertstate="firing", origin=~".+", service_id=~".+", service_name=~".+"}[1h])) by (alertname,origin,service_id,service_name)
    
    ##
    ## Criteria
    ##

    # Notice: some minimum level of traffic over time
    - record: fastly_origin:criteria_notice
      expr: min_over_time(fastly_origin:requests[5m]) > 1
    - record: fastly_origin:criteria_notice_recently
      expr: count_over_time(fastly_origin:criteria_notice[1h])

    # Warning: top 20% of notice
    - record: fastly_origin:criteria_warning
      expr: |
        topk(
          scalar(
            count(fastly_origin:criteria_notice) * .2
          ), sum(fastly_origin:criteria_notice) by (origin,service_id,service_name)
        ) or count(fastly_origin:alerts_recently) by (origin,service_id,service_name)
    - record: fastly_origin:criteria_warning_recently
      expr: count_over_time(fastly_origin:criteria_warning[1h])

    ##
    ## Alert Rules
    ## - Hold down timers / latch, for more details see
    ##   https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PrometheusAlertmanagerFlapping
    ## - Example: max_over_time(min_over_time(fastly_origin:4xx_ratio[3m])[10m:15s])
    ##   - Once the event persists for 3m
    ##   - Hold down / latch for 10m
    ##

    - alert: fastlyOrigin4xxPercent
      expr: |
        (
          max_over_time(
            min_over_time(fastly_origin:4xx_ratio[3m])[10m:15s]
          ) > fastly_origin:4xx_warn_ratio
        ) and (
          fastly_origin:criteria_warning_recently
          or count(fastly_origin:alerts_recently{alertname="fastlyOrigin4xxPercent"}) by (origin,service_id,service_name)
        )
      labels:
        job: 'fastlyOrigin'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyOrigin5xxPercent
      expr: |
        (
          max_over_time(
            min_over_time(fastly_origin:5xx_ratio[3m])[10m:15s]
          ) > fastly_origin:5xx_warn_ratio
        ) and (
          fastly_origin:criteria_warning_recently
          or count(fastly_origin:alerts_recently{alertname="fastlyOrigin5xxPercent"}) by (origin,service_id,service_name)
        )
      labels:
        job: 'fastlyOrigin'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyOriginErrorPercent
      expr: |
        (
          max_over_time(
            min_over_time(fastly_origin:errors_ratio[3m])[10m:15s]
          ) > fastly_origin:errors_warn_ratio
        ) and (
          fastly_origin:criteria_warning_recently
          or count(fastly_origin:alerts_recently{alertname="fastlyOriginErrorPercent"}) by (origin,service_id,service_name)
        )
      labels:
        job: 'fastlyOrigin'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyOriginP50Latency
      expr: |
        (
          max_over_time(
            min_over_time(fastly_origin:latency_p50_seconds[3m])[10m:15s]
          ) > fastly_origin:latency_p50_warn_seconds
        ) and (
          fastly_origin:criteria_warning_recently
          or count(fastly_origin:alerts_recently{alertname="fastlyOriginP50Latency"}) by (origin,service_id,service_name)
        )
      labels:
        job: 'fastlyOrigin'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
    - alert: fastlyOriginP99Latency
      expr: |
        (
          max_over_time(
            min_over_time(fastly_origin:latency_p99_seconds[3m])[10m:15s]
          ) > fastly_origin:latency_p99_warn_seconds
        ) and (
          fastly_origin:criteria_warning_recently
          or count(fastly_origin:alerts_recently{alertname="fastlyOriginP99Latency"}) by (origin,service_id,service_name)
        )
      labels:
        job: 'fastlyOrigin'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
